Created Searchplugin.java with default implementation
opensearch-project/opensearch-sdk-java pull request #387
Opened 2023-01-30 15:11 UTC by varuntumbe

Signed-off-by: Varun Hegde <varuntumbe@outlook.com>

### Description
Add a new interface SearchExtension with default implementations for extension points matching SearchPlugin.java.

### Issues Resolved
Copy pasted the default implementation of SearchPlugin.java ro SearchExtension.java 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-30 15:49 UTC, varuntumbe commented
Tell me If I have to add anything

Thanks and Regards
Varun

2023-01-30 16:14 UTC, dbwiddis reviewed
Thanks for this PR, @varuntumbe!

The code looks good.  There are some formatting tweaks (extra spaces, need a license header, need a newline at the end of file) that you should be able to fix by running `./gradlew spotlessApply` and committing the results.

2023-01-30 17:51 UTC, varuntumbe commented
Yes I applied the spotlessApply and RequireJavaDoc and Documentation linkage was giving build errors. I fixed it as of now temporarily. But  still it throws some warnings as no @return for methods.

Tell If anything else has to be done to close this, I will do one more of this #323 ( I already copied and just there to commit ) and next I will proceed to #319 If its okay.


Thanks and Regards
Varun

2023-01-30 17:55 UTC, dbwiddis commented
> Yes I applied the spotlessApply and RequireJavaDoc and Documentation linkage was giving build errors. I fixed it as of now temporarily. But still it throws some warnings as no @return for methods.

Yeah, you need `@param` and `@return` for constructors with parameters.   I think it's not required on the getters with same name as the field they are getting.

The one `@link` you removed goes to a not-yet-written `Extension` interface extension point, so for now to preserve the text could you just change what was `@link` to `@code` and we can put it back to link later?

2023-01-30 18:13 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +        public Map<String, Highlighter> getHighlighters() {
yes it does not need it for getter, I removed and its building fine

2023-01-30 18:13 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +         */
Done

2023-01-30 18:14 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +     * The executor service provider to be used at search
Yes, I can add that method to Extension Interface If its required.

2023-01-30 18:17 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +     * The executor service provider to be used at search
Sure no problem, I will paste that one

2023-01-30 18:55 UTC, dbwiddis requested changes
Thanks for your patience working through this!  A few javadoc nits.

2023-01-30 19:09 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/Extension.java
> +     * Provides the list of this plugin's custom thread pools, empty if
Oops did not notice this one. Fixed

2023-01-30 19:09 UTC, varuntumbe commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +         * Instantiates this object with the specified @param highlighters
Done

2023-01-30 19:15 UTC, varuntumbe commented
If there is anything left out, I will do it tomorrow. 

Thanks and Regards
Varun

2023-01-30 20:26 UTC, dbwiddis approved these changes

2023-01-30 22:13 UTC, joshpalis approved these changes
LGTM. Thanks for the effort @varuntumbe.

2023-01-30 22:28 UTC, merged

2023-01-31 03:01 UTC, varuntumbe commented
Thanks @joshpalis. I Hope to learn and contribute more in the future