Created ScriptExtension interface #318
opensearch-project/opensearch-sdk-java pull request #527
Opened 2023-03-06 18:37 UTC by petiveriaalliacea

### Description
Added a new interface ScriptExtension with the above two methods, with default implementations matching ScriptPlugin.java.

### Issues Resolved
#318 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-06 18:55 UTC, dbwiddis requested changes

2023-03-06 18:55 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/BaseExtension.java
> +public abstract class BaseExtension implements Extension, ActionExtension, ScriptExtension {
Don't add this here.  In fact, we actually need to remove `ActionExtension` but will do that elsewhere.

2023-03-06 18:55 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ScriptExtension.java
> +package org.opensearch.sdk;
Needs a license header. Running `./gradlew spotlessApply` should add it for you.

2023-03-06 18:56 UTC, dbwiddis requested changes
Also need to add tests for these extension points in `TestExtensionInterfaces`

2023-03-07 16:18 UTC, petiveriaalliacea commented
I can't run the test because of unexpected error:
```
D:\University\projects\opensearch-sdk-java\src\main\java\org\opensearch\sdk\TransportActions.java:58: error: incompatible types: Map<String,Class<? extends TransportAction<? extends ActionRequest,? extends ActionResponse>>> cannot be converted to Set<String>
                new RegisterTransportActionsRequest(uniqueId, transportActions),
```

![image](https://user-images.githubusercontent.com/77691894/223483041-bf18e887-d25e-4c9c-b980-a3f56da2a442.png)

2023-03-07 16:46 UTC, dbwiddis commented
> I can't run the test because of unexpected error:
> 
> ```
> D:\University\projects\opensearch-sdk-java\src\main\java\org\opensearch\sdk\TransportActions.java:58: error: incompatible types: Map<String,Class<? extends TransportAction<? extends ActionRequest,? extends ActionResponse>>> cannot be converted to Set<String>
>                 new RegisterTransportActionsRequest(uniqueId, transportActions),
> ```

That was a very recent change in [#6545](https://github.com/opensearch-project/OpenSearch/pull/6545) on the OpenSearch `main` branch (3.0.0-SNAPSHOT) and [#6556](https://github.com/opensearch-project/OpenSearch/pull/6556) for the 2.x branch.  

Make sure you have the latest snapshot (try clean, clear gradle cache, etc.) and it should work.  If that fails, you can fork OpenSearch main branch and do `./gradlew publishToMavenLocal` to get the latest bits in your local copy.

2023-03-07 17:52 UTC, dbwiddis commented
Tests were failing because #528 hadn't been merged. Should be fixed now.

2023-03-07 20:17 UTC, dbwiddis commented
Closing as this PR has been recreated in #534.  

In general, rebasing your branch to the current `main` branch is preferred to creating a new PR, and preserves the history of comments.  

No worries if you're new to Git or GitHub... my very first Github PR ended up being one of these close-and-resubmit things.

2023-03-07 20:17 UTC, closed without merging