Added IndexStoreExtension interface
opensearch-project/opensearch-sdk-java pull request #543
Opened 2023-03-09 13:49 UTC by nassipkali

### Description
This pr adds IndexStoreExtension

### Issues Resolved
#325 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-09 16:19 UTC, dbwiddis requested changes
Thanks for your contribution!  A few documentation tweaks needed.

2023-03-09 16:19 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/IndexStoreExtension.java
> +package org.opensearch.sdk;
Needs a license header.  Running `./gradlew spotlessApply` should add one automatically

2023-03-09 16:19 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/IndexStoreExtension.java
> + * A plugin that provides alternative directory implementations.
Replace `A plugin` with `An extension` in all the documents

2023-03-09 16:32 UTC, dbwiddis requested changes
Also please add some unit tests in `TestExtensionInterfaces` for the methods with default return values.

It's possible to test interfaces and their abstract methods with some mock/verify stuff, but I'm not sure that's necessary.

2023-03-09 16:33 UTC, dbwiddis commented
And, note that your commits need a DCO signoff. :)

2023-03-14 06:05 UTC, nassipkali commented
> Also please add some unit tests in `TestExtensionInterfaces` for the methods with default return values.
> 
> It's possible to test interfaces and their abstract methods with some mock/verify stuff, but I'm not sure that's necessary.

are my tests correct?

2023-03-14 17:57 UTC, ryanbogan approved these changes

2023-03-14 17:58 UTC, ryanbogan commented
Looks like it needs a rebase with main to address merge conflicts

2023-03-14 18:25 UTC, nassipkali commented
Sorry for review request flood. I thought that a review can be requested from several people at once

2023-03-14 18:28 UTC, dbwiddis commented
> Sorry for review request flood. I thought that a review can be requested from several people at once

Heh, no worries, we already get tons of email so this is barely a blip.  But everyone's already requested, you can re-request by clicking the little refresh icon next to someone who has reviewed.

![Screenshot 2023-03-14 at 11 27 35 AM](https://user-images.githubusercontent.com/9291703/225102611-ee0669bb-451e-4221-893c-03734335076f.png)

2023-03-14 18:30 UTC, dbwiddis requested changes
LGTM except for the incorrectly-deleted test annotation!

2023-03-14 18:30 UTC, dbwiddis commented on src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
> -    @Test
This shouldn't be removed.

2023-03-14 18:35 UTC, dbwiddis approved these changes
LGTM!

2023-03-14 18:38 UTC, ryanbogan approved these changes

2023-03-14 18:38 UTC, merged

2023-03-14 18:39 UTC, ryanbogan commented
@nassipkali Thanks for the contribution!