Persistent task
opensearch-project/opensearch-sdk-java pull request #562
Opened 2023-03-14 04:00 UTC by Kuanysh-kst

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-14 05:32 UTC, dbwiddis approved these changes
Thanks for this contribution! LGTM!

2023-03-14 05:51 UTC, Kuanysh-kst commented
it's normal that Gradle Build/check (pull_request) failed here

2023-03-14 06:08 UTC, dbwiddis commented
> is it normal that Gradle Build/check (pull_request) failed here

We just added a new way of javadoc checks in #551 and a choice I made when submitting that was to require `@param` entries for extension points with parameters.#543 

I'm not sure this was the best choice, given that we are copying existing docs from the plugin interfaces, but for now the best thing to do is to update the javadoc with `@param` tags for methods which take parameters.

2023-03-14 17:42 UTC, saratvemulapalli approved these changes
@Kuanysh-kst thanks for the contribution. 
Looks like there are conflicts with main, could you rebase?

2023-03-14 20:43 UTC, dbwiddis approved these changes

2023-03-14 20:48 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/PersistentTaskExtension.java
> +    default List<PersistentTasksExecutor<?>> getPersistentTasksExecutor(
We need to add `@param` javadocs for these parameters.

2023-03-14 20:49 UTC, dbwiddis requested changes
Build failing on missing params in javadocs.

2023-03-15 16:30 UTC, dbwiddis approved these changes
LGTM! Thanks!

2023-03-15 17:02 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/PersistentTaskExtension.java
> +        ClusterService clusterService,
Eventually, when this extension point is implemented, yes.  No need to change it now, though.

2023-03-16 00:54 UTC, owaiskazi19 approved these changes

2023-03-16 00:54 UTC, merged