[FEATURE] Create RepositoryExtension interfaceRepository
opensearch-project/opensearch-sdk-java pull request #564
Opened 2023-03-14 15:23 UTC by kokibas

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-14 17:34 UTC, dbwiddis requested changes

2023-03-14 17:34 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/RepositoryExtension.java
> +     *
You need `@param` tags for all of the arguments.

2023-03-14 17:34 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/RepositoryExtension.java
> +        return Collections.emptyMap();
Please add tests to `TestExtensionInterfaces` for these return values.

2023-03-16 09:26 UTC, closed without merging

2023-03-16 09:30 UTC, kokibas commented
I apologize, but I am very confused, I would like to make a new one and try again.If that s okay.

2023-03-16 17:11 UTC, dbwiddis commented
Sometimes that happens when you're learning git.  My very first github PR I ended up deleting and trying again. :)