Miscellaneous Spotbugs issues
opensearch-project/opensearch-sdk-java pull request #580
Opened 2023-03-17 08:35 UTC by Kuanysh-kst

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-17 19:33 UTC, dbwiddis requested changes
Thanks for your contribution and addressing some spotbugs issues.

There seem to be many more changes here not associated with spotbugs and some that I disagree with, though.   If these are a problem in spotbugs for some reason, please let me know what the issue is.

2023-03-17 19:33 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/SDKClient.java
> -            return new SDKClusterAdminClient(restHighLevelClient.cluster());
I'm not sure I like these changes.  Having a final field set in the constructor allows for more compiler optimizations than a nonfinal field with a setter.  Was this a spotbugs issue?

2023-03-17 19:33 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/SearchExtension.java
> +
We should leave the Extension interfaces exactly matching their plugin counterparts whenever possible.

Also this falls into the same category of my previous question, adding a setter that's not needed actually reduces the encapsulation and benefit of a final field.  Was this a spotbugs issue?

2023-03-17 19:33 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java
> -                default:
Usually spotbugs requires a default, not sure why you are removing it?

2023-03-17 19:33 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java
> +            logger.error(e.getMessage());
This may be a good change but don't think it's associated with spotbugs fixes?

2023-03-17 19:33 UTC, dbwiddis commented on src/test/java/org/opensearch/sdk/TestExtensionsRunner.java
> -        Principal userPrincipal = () -> "user1";
We actually want to leave this here as a placeholder, and it has the suppress warnings to indicate it's not a problem.

2023-03-17 19:33 UTC, dbwiddis commented on src/test/java/org/opensearch/sdk/TestSDKClusterService.java
> -        verify(extensionsRunner, times(0)).getExtensionTransportService();
Why are all these `verify()` calls being removed? They are an integral part of the test.

2023-03-18 09:34 UTC, Kuanysh-kst commented
Task :spotbugsMain
M V EI2: new org.opensearch.sdk.SDKClient$SDKClusterAdminClient(ClusterClient) may expose internal representation by storing an externally mutable object into SDKClient$SDKClusterAdminClient.clusterClient  At SDKClient.java:[line 475]
M V EI: org.opensearch.sdk.handlers.ExtensionDependencyResponseHandler.getExtensionDependencies() may expose internal representation by returning ExtensionDependencyResponseHandler.extensions  At ExtensionDependencyResponseHandler.java:[line 83]
M V EI: org.opensearch.sdk.ActionExtension$ActionHandler.getSupportTransportActions() may expose internal representation by returning ActionExtension$ActionHandler.supportTransportActions  At ActionExtension.java:[line 146]
M V EI: org.opensearch.sdk.handlers.ClusterStateResponseHandler.getClusterState() may expose internal representation by returning ClusterStateResponseHandler.clusterState  At ClusterStateResponseHandler.java:[line 79]
M V EI2: new org.opensearch.sdk.SearchExtension$FetchPhaseConstructionContext(Map) may expose internal representation by storing an externally mutable object into SearchExtension$FetchPhaseConstructionContext.highlighters  At SearchExtension.java:[line 853]
M V EI: org.opensearch.sdk.SearchExtension$FetchPhaseConstructionContext.getHighlighters() may expose internal representation by returning SearchExtension$FetchPhaseConstructionContext.highlighters  At SearchExtension.java:[line 857]
M V EI: org.opensearch.sdk.BaseExtension.extensionsRunner() may expose internal representation by returning BaseExtension.extensionsRunner  At BaseExtension.java:[line 65]
M V EI2: new org.opensearch.sdk.SDKClient$SDKIndicesClient(IndicesClient) may expose internal representation by storing an externally mutable object into SDKClient$SDKIndicesClient.indicesClient  At SDKClient.java:[line 498]
M V EI2: new org.opensearch.sdk.SDKClient$SDKRestClient(SDKClient, RestHighLevelClient) may expose internal representation by storing an externally mutable object into SDKClient$SDKRestClient.restHighLevelClient  At SDKClient.java:[line 330]
M V EI: org.opensearch.sdk.SearchExtension$PipelineAggregationSpec.getResultReaders() may expose internal representation by returning SearchExtension$PipelineAggregationSpec.resultReaders  At SearchExtension.java:[line 701]
M V EI: org.opensearch.sdk.SDKClient.initalizeJavaAsyncClient(String, int) may expose internal representation by returning SDKClient.javaAsyncClient  At SDKClient.java:[line 211]
M V EI: org.opensearch.sdk.SDKClient.initializeJavaClient(String, int) may expose internal representation by returning SDKClient.javaClient  At SDKClient.java:[line 186]
M V EI2: org.opensearch.sdk.SDKClient.initialize(Map) may expose internal representation by storing an externally mutable object into SDKClient.actions  At SDKClient.java:[line 101]
H C UMAC: Uncallable method org.opensearch.sdk.action.SDKActionModule$1ActionRegistry.register(ActionExtension$ActionHandler) defined in anonymous class  At SDKActionModule.java:[lines 73-74]
M V EI: org.opensearch.sdk.SearchExtension$AggregationSpec.getResultReaders() may expose internal representation by returning SearchExtension$AggregationSpec.resultReaders  At SearchExtension.java:[line 502]
M V EI2: new org.opensearch.sdk.NettyTransport(ExtensionsRunner) may expose internal representation by storing an externally mutable object into NettyTransport.extensionsRunner  At NettyTransport.java:[line 53]
M V EI: org.opensearch.sdk.action.SDKActionModule.getActions() may expose internal representation by returning SDKActionModule.actions  At SDKActionModule.java:[line 57]
M V EI: org.opensearch.sdk.ExtensionRestPathRegistry.getRegisteredPaths() may expose internal representation by returning ExtensionRestPathRegistry.registeredPaths  At ExtensionRestPathRegistry.java:[line 59]
M V EI: org.opensearch.sdk.ExtensionsRunner.getTaskManager() may expose internal representation by returning ExtensionsRunner.taskManager  At ExtensionsRunner.java:[line 617]
M V EI: org.opensearch.sdk.ExtensionsRunner.getExtensionNode() may expose internal representation by returning ExtensionsRunner.extensionNode  At ExtensionsRunner.java:[line 323]
M V EI: org.opensearch.sdk.ExtensionsRunner.getSdkActionModule() may expose internal representation by returning ExtensionsRunner.sdkActionModule  At ExtensionsRunner.java:[line 636]
M V EI2: org.opensearch.sdk.ExtensionsRunner.setExtensionNode(DiscoveryExtensionNode) may expose internal representation by storing an externally mutable object into ExtensionsRunner.extensionNode  At ExtensionsRunner.java:[line 314]
M V EI: org.opensearch.sdk.ExtensionsRunner.getNamedXContentRegistry() may expose internal representation by returning ExtensionsRunner.sdkNamedXContentRegistry  At ExtensionsRunner.java:[line 293]
M V EI: org.opensearch.sdk.ExtensionsRunner.getCustomNamedXContent() may expose internal representation by returning ExtensionsRunner.customNamedXContent  At ExtensionsRunner.java:[line 331]
M V EI: org.opensearch.sdk.ExtensionsRunner.getExtensionTransportService() may expose internal representation by returning ExtensionsRunner.extensionTransportService  At ExtensionsRunner.java:[line 640]
M V EI: org.opensearch.sdk.SDKClusterService.getClusterSettings() may expose internal representation by returning SDKClusterService.clusterSettings  At SDKClusterService.java:[line 78]
M V EI2: new org.opensearch.sdk.SDKClusterService(ExtensionsRunner) may expose internal representation by storing an externally mutable object into SDKClusterService.extensionsRunner  At SDKClusterService.java:[line 41]
M V EI2: new org.opensearch.sdk.handlers.ExtensionsInitRequestHandler(ExtensionsRunner) may expose internal representation by storing an externally mutable object into ExtensionsInitRequestHandler.extensionsRunner  At ExtensionsInitRequestHandler.java:[line 38]

2023-03-18 09:36 UTC, Kuanysh-kst commented
it was in spotBugs

2023-03-18 17:23 UTC, dbwiddis commented
Hey @Kuanysh-kst, first I do want to thank you for contributing and trying to address the spotbugs issues!  Your help really is appreciated.

I also want to thank you for going above and beyond the bugs I listed in #552, the initiative to try to fix all the issues is welcome.

All that said, a few points:
 - Reviewing PRs that touch a lot of files and cover a lot of different types of fixes is hard for maintainers.  
   - That makes it difficult to review in logical steps, like all of a certain type of issue at the same time.
   - That makes us unable to approve some of the fixes we agree with, while continuing to discus the ones we might be less confident in approving
   - Sometimes you can mitigate the complexity by making more frequent small commits covering each type, so we can review by commit instead of the entire diff at the end.  But in your case there are a lot of commits in the history because you didn't start with a clean checkout from the latest `main` branch, so that's not an option.  This PR lists 34 changed files and covers a lot of different types of changes, most of them from previous merged commits.  It's somewhat impossible to even review at this point.
   - Another alternative you can consider is separate PRs covering a subset of the issues.   That was what I had in mind when I posted #552, that several different contributors could X-off one or two or a category of issues.  Or even if you fixed all of them, it was a much smaller number of files needing fixed so it could be reviewed more easily.
   - And I had intentionally already filtered out most of the "expose internal representation" issues because not all of them were problems that needed fixing. I had planned on following up with a later issue or PR on those myself, after taking the time to evaluate each one.

Addressing the subject of "expose internal representation", note that SpotBugs is a static analysis tool. It doesn't know what you mean, only what the code says.  Many of these issues exist because of a combination of a variable being declared `final`, having a getter, and being a structure that allows modification of values (array, list, map, etc.).  Removing `final` and adding a setter may make the spotbugs issue go away, but it does not fix the problem. It just makes the mutability look intentional so spotbugs ignores it, and is more likely than not the incorrect solution (although it might be in some cases... but it'd be nice to review those separately from everything else).

So a request, please:
 - either rebase this PR to main, or if it's too far gone at this point, just close it and create a new branch after updating your `main` branch
 - submit a separate PR (or change this PR) a smaller number of fixes, starting with the ones in #552, and following up with a later PR with any other bugs, trying to limit either the number of files changed, or the type of issue resolved
   - some of those "mutable" fixes need to be changed, let's save those for a separate PR
   - don't remove `final` and add setters unless you're sure that's what's intended, which it usually is not
   - feel free to ask about suggested fixes on the issue so we can discuss the correct approach.  For example, in "response handlers" there are often these "mutable" objects in getters, but they are produced exactly once, read exactly once, and it's not a problem if someone changes the object later as it's never referred to again.   It's possible to configure spotbugs to ignore these types of issues and we can look into that... it'd be a good change and we could leave spotbugs up all the time (my end goal).   For now, though, I'm trying to clear out the noise first.

2023-03-18 17:29 UTC, closed without merging