Created ExtensibleExtension interface
opensearch-project/opensearch-sdk-java pull request #600
Opened 2023-03-22 20:52 UTC by bexultantokan

### Description
Copied the content of the ExtensiblePlugin and pasted it to the new ExtensibleExtension file. Changed the wording from "plugin" to "extension."

### Issues Resolved
Created the interface to help move away from plugins to extensions.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-22 22:43 UTC, saratvemulapalli commented
@dbwiddis @owaiskazi19 do we need `loadExtensions` to be supported by extensions? 
Sounds like a feature where extensions can be built on top of extensions?

2023-03-23 18:00 UTC, owaiskazi19 commented
> @dbwiddis @owaiskazi19 do we need `loadExtensions` to be supported by extensions? Sounds like a feature where extensions can be built on top of extensions?

Is this similar to having dependent extensions for an extension?

2023-03-24 04:22 UTC, dbwiddis commented
> @dbwiddis @owaiskazi19 do we need `loadExtensions` to be supported by extensions? Sounds like a feature where extensions can be built on top of extensions?

Yeah it seems like a way to say "hey, look at my `getActions()` and you can also use the `getActions()` from these other extensions.   I can see some use cases for "dependent extensions" which are tightly integrated with each other.

2023-03-24 04:23 UTC, dbwiddis reviewed
LGTM except need to run spotless to fix formatting.

2023-03-24 04:23 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ActionExtension.java
> +
The little red symbol here tells me this file doesn't end with the proper end of file marker.   And sure enough, it's failing the spotless check in CI.   Running `./gradlew spotlessApply` will fix this.

2023-03-24 04:24 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ActionExtension.java
> +
Actually, you shouldn't be changing this file at all!

2023-03-26 12:16 UTC, bexultantokan commented
Hello @dbwiddis , could you please review my latest commit?

2023-03-26 15:39 UTC, dbwiddis requested changes
Looks good other than the annotation that doesn't work here.

2023-03-26 15:39 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ExtensibleExtension.java
> + * @opensearch.api
SDK doesn't use this annotation so it will fail compiling.  Please remove this.

We use package-based API definitions.

2023-03-26 15:39 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ExtensibleExtension.java
> +     * @opensearch.api
Same here.

2023-03-29 17:26 UTC, bexultantokan commented
@dbwiddis could you review the recent changes, please? Much appreciated.

2023-03-29 17:35 UTC, dbwiddis requested changes
Sorry if the previous review wasn't clear, it was only the `@opensearch.api` annotation that needed to be deleted.  The class itself needs the rest of that javadoc.

2023-04-03 14:43 UTC, dbwiddis approved these changes
LGTM!

2023-04-03 16:58 UTC, ryanbogan approved these changes

2023-04-03 16:58 UTC, ryanbogan commented
Thanks for the contribution!

2023-04-03 16:59 UTC, merged