Sdk api
opensearch-project/opensearch-sdk-java pull request #650
Opened 2023-04-05 16:47 UTC by kokibas

### Description
Move all the extensions interface under a same directory

### Issues Resolved
#599 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-05 17:21 UTC, dbwiddis requested changes
I'm not sure what the `RepositoryExtension` class is or why ActionExtension is there.  It should be just like all the other extensions and get moved into the `.api` directory.

2023-04-05 17:21 UTC, dbwiddis commented on src/main/java/org/opensearch/sdk/ActionExtension.java
> -package org.opensearch.sdk;
This should have been moved into `org.opensearch.sdk.api` with all the rest.  Where did it go?

2023-04-05 17:21 UTC, dbwiddis commented on CREATE_YOUR_FIRST_EXTENSION.md
> +import org.opensearch.sdk.RepositoryExtension.ActionExtension;
I"m not sure what `RepositoryExtension` is as it's not part of this PR.  But that class should have been moved into the `.api` package with all the rest, and all these import changes should be `import org.opensearch.sdk.api.ActionExtension;`

2023-04-05 17:21 UTC, dbwiddis commented on src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java
> -    @Test
we shouldn't be deleting tests

2023-04-05 20:14 UTC, dbwiddis requested changes
One last change please!

2023-04-05 20:14 UTC, dbwiddis commented on CREATE_YOUR_FIRST_EXTENSION.md
> +import org.opensearch.sdk.api.*;
We prohibit star imports in our code, so just make this `org.opensearch.sdk.api.ActionExtension`.

2023-04-06 17:21 UTC, owaiskazi19 submitted a review, later dismissed
Just one change that @dbwiddis has pointed already. Rest LGTM! Thanks @kokibas for cleaning it up

2023-04-07 15:09 UTC, dbwiddis approved these changes
LGTM!

2023-04-07 16:27 UTC, owaiskazi19 approved these changes

2023-04-07 16:28 UTC, merged